name:  Publish

on:
  workflow_dispatch:  
  push:
    branches:
    - master
    - main



jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.1.x'
          
      - name: Restore
        run: dotnet restore ./StufShop.sln
        
      - name: Build
        run: dotnet build ./StufShop.sln --configuration Release --no-restore
 
      - name: Publish
        run: dotnet publish ./StufShop.sln --configuration Release --no-build
